#!/bin/bash

export BINUTILSVER=${BINUTILSVER:=2.44}
export BINUTILSREV=${BINUTILSREV:=}
export GCCVER=${GCCVER:=16.1.0}
export GCCREV=${GCCREV:=}
export NEWLIBVER=${NEWLIBVER:=4.6.0}
export NEWLIBREV=${NEWLIBREV:=.20260123}
export MPCVER=${MPCVER:=1.3.1}
export MPCREV=${MPCREV:=}
export MPFRVER=${MPFRVER:=4.2.2}
export MPFRREV=${MPFRREV:=}
export GMPVER=${GMPVER:=6.3.0}
export GMPREV=${GMPREV:=}
#export GDBVER=${GDBVER:=14.2}
export GDBREV=${GDBREV:=}

export AUTOMAKE_MIN_VERSION=1.17
# Backward compatibility for older scripts/environments
export REQUIRED_AUTOMAKE_VERSION=${REQUIRED_AUTOMAKE_VERSION:-$AUTOMAKE_MIN_VERSION}

export ENABLE_BOOTSTRAP=${ENABLE_BOOTSTRAP:=0}
export ENABLE_DOWNLOAD_CACHE=${ENABLE_DOWNLOAD_CACHE:=1}
export ENABLE_STATIC_BUILD=${ENABLE_STATIC_BUILD:=0}

# Download settings
export DOWNLOAD_RETRIES=${DOWNLOAD_RETRIES:=3}
export DOWNLOAD_RETRY_DELAY=${DOWNLOAD_RETRY_DELAY:=10}
export DOWNLOAD_CONNECT_TIMEOUT=${DOWNLOAD_CONNECT_TIMEOUT:=30}

export ENABLE_VERBOSE_BUILD=${ENABLE_VERBOSE_BUILD:=1}

exec "$@"
